### ISSUE TITLE
Participant feedback tracking

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/p2p-internet-workshop#49]
## Feedback about module-1 IPFS worksheet

- [ ] The `fc00::/8` notation is confusing, it is unclear that a cjdns address of the form `fc7d:1633:...` is a match

- [ ] Line breaks on the sheet is still a little confusing

- [ ] This step in module-1 needs some example:
    >Now let's add some content on example2, then type exit twice to return to example, and try to read that text back on example and from your browser. It may take a while after you first establish peering, but eventually the content will become available across the network.

- [ ] Can we hide to docker layer? The SSH layer + docker layer is confusing. (e.g. hide it behind a program, not use docker altogether)

- [ ] A cooler app (e.g. text chat with pubsub), note that SSB + Patchfoo integration is already underway

## Known issues that occasionally occur and can be addressed by node reboot

- [ ] Node boots up with Access Point name as `test2`

- [ ] One incident with `EOF` error when loading ipfs docker

**Comment by VictorBjelkholm** [comment]
(IPFS specific) Replace `ipfs bootstrap add` with `ipfs swarm connect` to get immediate feedback if working or not (`swarm connect` will print failure/success compared to `bootstrap add` which always show success as long as the Multiaddr is correct)
